
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[391] =
    {   0,
        0,    0,    0,    0,    0,    0,   71,   69,   60,   59,
       52,   69,   57,   49,   53,   69,   56,   49,   49,   57,
       49,   56,   49,   42,   43,   57,   51,   50,   51,   57,
       58,   58,   69,   53,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       53,   53,   57,    3,    3,    3,   67,   68,   51,    0,
       48,    0,    0,   57,    0,    0,    0,    0,   55,   50,
       55,   52,   50,    0,    0,   54,   56,    0,   45,    1,
        0,   45,   42,    0,    0,   42,   42,    0,   42,   43,
       43,   43,   43,   53,   53,   58,    0,    0,    0,    0,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   33,
       58,   58,   58,   58,   58,   58,   37,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,    0,    0,
        0,    3,    3,    2,   67,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   47,    0,    0,    0,    0,
        0,   45,    0,    4,    0,   46,   42,   42,   42,   42,
       44,   43,   43,   43,   43,    0,    0,    0,    0,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   35,   58,   58,   16,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,

       58,   58,   58,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   61,    0,    0,    0,    0,    0,    0,
       45,   46,   42,   44,   44,   44,   43,    0,    0,    0,
        0,   58,   58,   58,    8,   58,   30,    9,   58,   58,
       58,   58,   34,   12,   58,   58,   36,   58,   17,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   27,   58,   58,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   44,   44,   44,
       44,    0,    0,    0,    0,    5,   58,   58,   29,   10,
       58,   58,   58,   58,   14,   58,   58,   58,   58,   20,

       58,   58,   58,   58,   58,   58,   25,   58,   58,   41,
        0,    0,    0,    0,    0,   62,    0,    0,   65,    0,
        0,   44,    0,    0,    0,   58,   58,   58,   58,   58,
       11,   13,   15,   58,   58,   38,   21,   39,   22,   23,
       40,   58,   58,   58,    0,    0,    0,    0,    0,   63,
        0,    0,    0,    0,   58,   58,   58,   32,   58,   58,
       24,   58,   58,    0,    0,    0,   64,    0,    0,    0,
        6,   58,   31,   18,   19,   26,   28,    0,    0,    0,
        0,    0,   58,    0,   66,    0,    0,    0,    7,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   28,   31,   32,
       33,   33,   34,   33,   33,   35,   33,   33,   33,   33,
       33,   33,   33,   33,   36,   33,   33,   37,   33,   33,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   33,   52,   53,   54,   55,
       56,   57,   33,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    5,    5,
        6,    1,    1,    1,    1,    7,    8,    6,    6,    6,
        6,    6,    9,    9,    9,   10,   10,    1,   10,    1,
        1,    9,    5,    5,    6,    6,    6,    5,    9,    9,
        9,    9,    9,    9,   10,    9,    9,   10,    9,   10,
       10,   10,    9,   10,    9,    9,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[453] =
    {   0,
        0,  959,   68,   69,   67,   68,  965,  967,  967,  967,
      939,   69,   72,   58,   76,  924,  967,  937,   63,  967,
       70,   70,   79,  109,   86,  935,   90,  935,   74,  937,
      919,   72,   66,  932,  102,   74,   85,   99,  111,  113,
       81,  109,  121,  115,  112,  124,  114,  125,  122,  133,
      132,  967,  184,  953,  952,  936,    0,  967,  967,  175,
      967,  175,  181,  967,  906,  137,  904,  900,  942,  967,
      967,  967,  967,  179,  179,  967,  967,  932,  225,  967,
      945,  232,  267,  186,  205,  161,  167,    0,  205,  274,
      213,  194,  229,  922,  921,  906,  177,  203,    0,    0,

      154,  215,  169,  216,  222,  211,  238,  220,  244,  143,
      257,  250,  258,  261,  265,  262,  905,  273,  260,  280,
      268,  292,  291,  274,  293,  297,  304,  303,  342,  343,
       61,  940,  939,  967,    0,  332,    0,    0,    0,  893,
      881,  893,  935,  882,  914,  967,  343,    0,    0,    0,
      345,  967,  932,  967,  348,  353,  334,  967,  899,  880,
      344,  339,  967,  897,  878,    0,    0,    0,    0,  321,
      337,  344,  342,  360,  339,  353,  363,  365,  368,  370,
      371,  374,  375,  891,  376,  377,  890,  380,  385,  381,
      387,  388,  392,  391,  394,  395,  398,  396,  401,  400,

      403,  416,  411,  873,  882,  446,    0,  480,    0,  875,
      878,  873,  920,  967,  875,  443,    0,  519,    0,  448,
      483,  967,  967,  409,  425,  435,  967,    0,    0,    0,
        0,  422,  433,  434,  882,  435,  881,  880,  437,  438,
      445,  440,  879,  878,  455,  456,  722,  452,  720,  475,
      459,  483,  482,  496,  481,  441,  223,  507,  514,  506,
      505,  719,  516,  530,  703,  550,    0,    0,    0,  697,
      747,  701,  744,  298,    0,    0,    0,  469,  967,  706,
      683,    0,    0,    0,    0,  689,  518,  529,  683,  682,
      520,  531,  534,  533,  672,  535,  539,  540,  546,  638,

      544,  547,  548,  553,  555,  557,  637,  559,  558,  636,
      613,    0,    0,  626,  669,  967,  668,  667,  967,    0,
        0,  967,    0,    0,    0,  630,  561,  563,  564,  567,
      629,  628,  627,  568,  571,  626,  625,  624,  622,  618,
      616,  572,  582,  573,  606,    0,  611,  648,  643,  967,
        0,  609,    0,    0,  583,  585,  584,  606,  591,  593,
      605,  594,  595,  596,    0,  635,  967,    0,    0,    0,
      494,  596,  493,  442,  345,  267,  162,  635,    0,    0,
        0,    0,  597,  654,  967,    0,    0,    0,   71,  967,
      678,  688,  698,  708,  714,  724,  734,  743,  752,  762,

      768,  770,  772,  774,  776,  778,  784,  790,  792,  794,
      796,  798,  800,  802,  804,  806,  808,  810,  812,  814,
      816,  818,  820,  822,  828,  838,  844,  846,  848,  850,
      852,  854,  856,  858,  864,  870,  872,  874,  876,  878,
      880,  886,  892,  894,  896,  898,  900,  902,  904,  906,
      908,  910
    } ;

static yyconst flex_int16_t yy_def[453] =
    {   0,
      390,    1,  391,  391,  392,  392,  390,  390,  390,  390,
      390,  393,  390,  390,  390,  394,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      395,  395,  390,  390,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      390,  390,  390,  396,  396,  390,  397,  390,  390,  393,
      390,  398,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  394,  399,  390,  390,  390,  390,  390,
      400,  390,  390,  390,  390,  390,  390,  401,  390,  390,
      390,  390,  390,  390,  390,  395,  390,  393,  402,  403,

      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  390,  390,
      390,  396,  396,  390,  397,  393,  404,  405,  406,  390,
      390,  390,  407,  390,  390,  390,  394,  408,  409,  410,
      390,  390,  400,  390,  390,  390,  390,  390,  390,  390,
      401,  390,  390,  390,  390,  411,  412,  413,  414,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,

      395,  395,  395,  390,  390,  393,  415,  393,  416,  390,
      390,  390,  407,  390,  390,  394,  417,  394,  418,  390,
      390,  390,  390,  390,  390,  390,  390,  419,  420,  421,
      422,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  390,  393,  423,  208,  424,  390,
      425,  390,  426,  394,  427,  218,  428,  390,  390,  390,
      390,  429,  430,  431,  432,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,

      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      390,  433,  434,  390,  425,  390,  435,  426,  390,  436,
      437,  390,  438,  439,  440,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  390,  441,  393,  442,  435,  390,
      443,  394,  444,  445,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  390,  446,  442,  390,  447,  448,  449,
      395,  395,  395,  395,  395,  395,  395,  390,  450,  451,
      452,  432,  395,  390,  390,  434,  437,  439,  395,    0,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,

      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390
    } ;

static yyconst flex_uint16_t yy_nxt[1038] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       25,   26,   20,   27,   28,   29,   30,   31,   31,   31,
       31,   31,   31,   31,   32,   31,   31,   17,   33,   17,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   31,
       43,   31,   44,   31,   31,   31,   31,   45,   46,   47,
       48,   49,   50,   31,   31,   31,   17,   51,   17,   52,
       55,   55,   58,   58,   61,   63,   76,   98,   64,   69,
       56,   56,   70,   71,   72,   76,   78,   70,   79,   79,
       79,   80,   58,   58,   70,   77,   81,   71,   59,   95,

       73,   99,   82,   70,   90,   90,   90,   62,  143,   97,
       97,   71,   97,   94,   59,  205,   85,   65,   66,   97,
       91,   92,   67,   97,   68,   82,  100,   83,   83,   84,
      101,  102,   85,  114,  104,  103,  115,   97,   93,   85,
       97,  106,  105,   86,   87,   88,   92,   97,  107,   97,
       97,   97,   97,   97,  108,   85,   70,  109,  120,   97,
       97,   89,   97,   97,  116,  111,  110,  112,  117,   87,
      119,   97,   88,  121,  122,  118,  113,  127,  125,  126,
       61,   97,  128,  123,   63,  129,  124,  130,  146,  141,
       64,  142,   97,  136,  136,  157,  158,  147,  147,   72,

       97,  159,   82,  179,   84,   84,   84,   97,   61,  170,
      137,  138,  166,   62,  148,  149,   85,   75,  155,  160,
      155,  158,  172,  156,  156,  156,   65,   66,  164,   65,
       66,   67,   85,   68,  131,  139,   68,  167,  138,  150,
      158,   62,  149,   79,   79,   79,  165,  162,  163,   97,
       79,   79,   79,   97,   97,  151,  152,  157,   97,  152,
       97,   97,  151,  152,  163,  158,  152,  304,  174,  175,
      171,  151,  152,  163,  177,  173,   97,  152,  151,  152,
      176,  162,   97,   82,  152,   83,   83,   84,   97,  163,
       82,  178,   90,   90,   90,   97,   97,   85,   97,   97,

       97,   86,   87,   97,   85,   97,   97,  146,   91,   92,
      181,   97,   97,   85,  188,  180,  183,  182,   97,   89,
       85,  185,  184,  192,  197,  186,   93,   87,  189,   97,
       97,   97,  187,  195,   92,   97,   75,   61,  190,  191,
      193,   97,   97,  129,  129,  129,  130,  199,  196,  198,
      206,  206,  146,  203,  201,  200,  202,  194,  220,   97,
      220,  216,  216,  221,  221,  221,  156,  156,  156,  158,
       62,  156,  156,  156,  163,   97,  232,   97,  224,  225,
       97,   75,   97,   97,  222,  237,  234,  222,   65,   66,
      233,   97,  204,  131,  158,   68,  226,  235,   97,  163,

      222,   97,  236,   97,  225,  222,   97,  241,   97,   97,
      238,  242,   97,   97,   97,   97,  243,  246,   97,   97,
      245,  239,  240,   97,  244,   97,   97,  248,  249,   97,
       97,  247,   97,   97,   97,  250,   97,  255,   97,   97,
      251,   97,  259,  278,  279,  253,  254,  252,  262,   97,
      261,   61,  146,  256,   97,  257,  260,  258,  263,  280,
       97,  274,  274,  264,  266,  266,  221,  221,  221,  279,
      279,   97,   97,   97,  286,   97,   97,  281,   97,   97,
       97,   75,  288,   97,   62,   61,  289,  278,  291,  287,
       97,  303,  293,   97,   97,  279,  290,   97,  268,  268,

      268,  221,  221,  221,  279,  292,  296,  268,  268,  268,
      268,  268,  294,   97,  152,  295,  298,  152,   62,   97,
       97,   97,  268,  268,  268,  268,  268,  268,  146,  279,
      152,   97,   97,  297,   97,  152,  302,  276,  276,  276,
      299,  300,  301,   97,   97,   97,  276,  276,  276,  276,
      276,  305,   97,  308,   97,   61,   97,   75,   97,  306,
      307,  276,  276,  276,  276,  276,  276,   97,   97,   97,
      327,   97,   97,   97,  329,  309,  310,   97,   97,  328,
      331,  333,   97,  330,   97,   97,   97,  332,   62,  337,
      335,   97,  339,   97,  338,   97,   97,   97,  334,   97,

      336,   97,   97,  342,  341,   97,   97,  355,  344,   97,
       97,   97,  340,  343,  359,  360,   61,  356,  146,  361,
       97,   97,   97,   97,  357,  363,  358,  372,  362,   97,
      373,   97,   97,   97,   97,   97,  384,  367,  384,  376,
      385,  377,  378,   97,   97,  350,  371,   75,  374,   62,
      367,  364,  375,  383,   97,  384,   97,  384,  385,  385,
       97,  389,   97,   97,   97,   97,   97,   97,   97,  319,
      350,  316,  348,  345,   97,   97,   97,  385,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   60,   60,

       60,   60,   60,   60,   60,   60,   60,   60,   74,   74,
       97,   74,   74,   74,   74,   74,   74,   74,   96,   96,
       97,   97,   96,   96,  132,  132,  132,   97,  132,  132,
      132,  132,  132,  132,  135,  322,  135,  135,  135,  135,
      322,  135,  135,  135,   60,   60,  319,   60,  317,  316,
       60,  314,   60,   74,   74,  311,   74,   97,   97,   74,
       97,   74,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  161,  161,  168,  168,  169,  169,  207,  207,
      208,  208,  209,  209,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  217,  217,  218,  218,  219,  219,

      228,  228,  229,  229,  230,  230,  231,  231,  267,  267,
      269,  269,  275,  275,  277,  277,  282,  282,  283,  283,
      284,  284,  285,  285,  312,  312,  313,  313,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  320,  320,
      321,  321,  323,  323,  324,  324,  325,  325,  326,  326,
      346,  346,  347,  347,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  351,  351,  352,  352,  353,  353,
       96,   96,  354,  354,  365,  365,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  368,  368,  369,  369,

      370,  370,  379,  379,  380,  380,  381,  381,  382,  382,
      386,  386,  387,  387,  388,  388,   97,   97,   97,   97,
       97,  273,  214,  272,  271,  270,  265,  205,   97,   97,
      227,  227,  223,  223,  154,   71,  215,  214,  212,  211,
      210,  133,  133,   97,   97,   70,   70,  154,   64,  145,
      144,  143,  140,  134,  133,  133,   73,   97,   71,   59,
       71,   70,   75,   59,  390,   53,    7,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,

      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390
    } ;

static yyconst flex_int16_t yy_chk[1038] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    5,    6,   12,   13,   19,   32,   13,   14,
        3,    4,   14,   14,   15,   21,   22,   19,   22,   22,
       22,   23,    5,    6,   21,   21,   23,   27,   29,   29,

       15,   33,   25,   23,   25,   25,   25,   12,  131,  389,
       32,   27,   36,   27,   27,  131,   25,   13,   13,   41,
       25,   25,   13,   37,   13,   24,   33,   24,   24,   24,
       35,   35,   25,   41,   36,   35,   41,   38,   25,   24,
       35,   38,   37,   24,   24,   24,   25,   42,   38,   39,
       45,   40,   47,   44,   38,   24,   51,   39,   45,   43,
       49,   24,   46,   48,   42,   40,   39,   40,   43,   24,
       44,   50,   24,   46,   46,   43,   40,   49,   47,   48,
       60,  110,   50,   46,   63,   53,   46,   53,   74,   66,
       53,   66,  101,   62,   62,   86,   86,   75,   75,   51,

      377,   87,   84,  110,   84,   84,   84,  103,   98,  101,
       62,   62,   97,   60,   75,   75,   84,   74,   85,   87,
       85,   86,  103,   85,   85,   85,   63,   63,   92,   53,
       53,   63,   84,   63,   53,   62,   53,   97,   62,   75,
       89,   98,   75,   79,   79,   79,   92,   91,   91,  106,
       82,   82,   82,  102,  104,   79,   79,   89,  108,   79,
      105,  257,   82,   82,   93,   89,   82,  257,  105,  106,
      102,   79,   79,   91,  108,  104,  107,   79,   82,   82,
      107,   93,  109,   83,   82,   83,   83,   83,  112,   93,
       90,  109,   90,   90,   90,  111,  113,   83,  119,  114,

      116,   83,   83,  115,   90,  376,  121,  274,   90,   90,
      112,  118,  124,   83,  119,  111,  114,  113,  120,   83,
       90,  116,  115,  121,  124,  118,   90,   83,  120,  123,
      122,  125,  118,  123,   90,  126,  274,  136,  120,  120,
      122,  128,  127,  129,  130,  129,  130,  126,  123,  125,
      136,  136,  147,  128,  127,  126,  127,  122,  151,  170,
      151,  147,  147,  151,  151,  151,  155,  155,  155,  157,
      136,  156,  156,  156,  162,  171,  170,  175,  161,  161,
      173,  147,  172,  375,  156,  175,  172,  156,  130,  130,
      171,  176,  129,  130,  157,  130,  161,  173,  174,  162,

      156,  177,  174,  178,  161,  156,  179,  178,  180,  181,
      176,  179,  182,  183,  185,  186,  180,  183,  188,  190,
      182,  177,  177,  189,  181,  191,  192,  186,  188,  194,
      193,  185,  195,  196,  198,  189,  197,  194,  200,  199,
      190,  201,  198,  224,  224,  192,  193,  191,  201,  203,
      200,  206,  216,  195,  202,  196,  199,  197,  202,  225,
      232,  216,  216,  203,  206,  206,  220,  220,  220,  224,
      226,  233,  234,  236,  232,  239,  240,  225,  242,  256,
      374,  216,  234,  241,  206,  208,  236,  226,  240,  233,
      248,  256,  242,  245,  246,  226,  239,  251,  208,  208,

      208,  221,  221,  221,  278,  241,  248,  208,  208,  208,
      208,  208,  245,  250,  221,  246,  251,  221,  208,  255,
      253,  252,  208,  208,  208,  208,  208,  208,  218,  278,
      221,  373,  371,  250,  254,  221,  255,  218,  218,  218,
      252,  253,  254,  261,  260,  258,  218,  218,  218,  218,
      218,  258,  259,  261,  263,  266,  287,  218,  291,  259,
      260,  218,  218,  218,  218,  218,  218,  288,  264,  292,
      287,  294,  293,  296,  291,  263,  264,  297,  298,  288,
      293,  296,  301,  292,  299,  302,  303,  294,  266,  301,
      298,  304,  303,  305,  302,  306,  309,  308,  297,  327,

      299,  328,  329,  306,  305,  330,  334,  327,  309,  335,
      342,  344,  304,  308,  334,  335,  347,  328,  352,  342,
      343,  355,  357,  356,  329,  344,  330,  356,  343,  359,
      357,  360,  362,  363,  372,  383,  378,  366,  378,  362,
      378,  363,  364,  361,  358,  349,  355,  352,  359,  347,
      348,  345,  360,  372,  341,  384,  340,  384,  378,  384,
      339,  383,  338,  337,  336,  333,  332,  331,  326,  318,
      317,  315,  314,  311,  310,  307,  300,  384,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  393,  393,

      393,  393,  393,  393,  393,  393,  393,  393,  394,  394,
      295,  394,  394,  394,  394,  394,  394,  394,  395,  395,
      290,  289,  395,  395,  396,  396,  396,  286,  396,  396,
      396,  396,  396,  396,  397,  281,  397,  397,  397,  397,
      280,  397,  397,  397,  398,  398,  273,  398,  272,  271,
      398,  270,  398,  399,  399,  265,  399,  262,  249,  399,
      247,  399,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  401,  401,  402,  402,  403,  403,  404,  404,
      405,  405,  406,  406,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  408,  408,  409,  409,  410,  410,

      411,  411,  412,  412,  413,  413,  414,  414,  415,  415,
      416,  416,  417,  417,  418,  418,  419,  419,  420,  420,
      421,  421,  422,  422,  423,  423,  424,  424,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  427,  427,
      428,  428,  429,  429,  430,  430,  431,  431,  432,  432,
      433,  433,  434,  434,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  436,  436,  437,  437,  438,  438,
      439,  439,  440,  440,  441,  441,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  443,  443,  444,  444,

      445,  445,  446,  446,  447,  447,  448,  448,  449,  449,
      450,  450,  451,  451,  452,  452,  244,  243,  238,  237,
      235,  215,  213,  212,  211,  210,  205,  204,  187,  184,
      165,  164,  160,  159,  153,  145,  144,  143,  142,  141,
      140,  133,  132,  117,   96,   95,   94,   81,   78,   69,
       68,   67,   65,   56,   55,   54,   34,   31,   30,   28,
       26,   18,   16,   11,    7,    2,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,

      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "CCode.l"


/*Universal char name*/
/*float exponente*/
/*int length*/
#line 17 "CCode.l"
	#include <stdio.h>
	#include <string.h>

	struct Token EmptyStruct;
	void escribir_tex(struct Token t);
	void new_frame();
	void cerrar_frame();
	void crear_archivo_salida();
	void cerrar_archivo_salida();
	void contador_tokens(int id);
	void str_replace(char *target, const char *needle, const char *replacement);
	void hacer_grafico_histo1();
	void hacer_grafico_histo2(int secuencia,int maximo);
	void grafico_pie();
	

	enum tokentype{
		KEYWORD = 258, //(8) declarativo y de control
		IDENTIFIER = 260,    //(1) 
		NUMBER = 261, //(2)  INTD decimal, INTO octal, INTH hexadecimal, FLOATD decimal, FLOATE exponente, FLOATH hexadecimal
		STRINGLITERAL = 262,	    //(3) STRL, CHARL
		OPERADOR = 263,	    //(4)
		PUNCTUATOR = 264,     //(5) PUNTAC PUNT
		NL = 265,	    //(6)
		END = 266	    //(7)
	};

	struct Token {
		int id;
		char* lexema; //guarda el valor tipo string
		int valor; //guarda el valor tipo numerico
		char tipo[9]; //siglas
	};

	char* lexema_actual;
	int valor_actual = -1;
	char tipo_actual[9] = {0};
	int id_actual = -1;
	int termino = 0;
	FILE *archivo_salida;
	int id8 = 0;
	int id1 = 0;
	int id2 = 0;
	int id3 = 0;
	int id4 = 0;
	int id5 = 0;
	float idf1,idf2,idf3,idf4,idf5,idf8;

	int defining; //para ver si el nombre es una definicion
#line 894 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define IFILE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 69 "CCode.l"


#line 1120 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 391 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 967 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 71 "CCode.l"
{BEGIN(COMMENT);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 72 "CCode.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 73 "CCode.l"
{}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 74 "CCode.l"
{printf("Comentario sin terminar\n");}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 75 "CCode.l"
{}
	YY_BREAK
case 5:
#line 79 "CCode.l"
case 6:
#line 80 "CCode.l"
case 7:
#line 81 "CCode.l"
case 8:
#line 82 "CCode.l"
case 9:
#line 83 "CCode.l"
case 10:
#line 84 "CCode.l"
case 11:
#line 85 "CCode.l"
case 12:
#line 86 "CCode.l"
case 13:
#line 87 "CCode.l"
case 14:
#line 88 "CCode.l"
case 15:
#line 89 "CCode.l"
case 16:
#line 90 "CCode.l"
case 17:
#line 91 "CCode.l"
case 18:
#line 92 "CCode.l"
case 19:
#line 93 "CCode.l"
case 20:
#line 94 "CCode.l"
case 21:
#line 95 "CCode.l"
case 22:
#line 96 "CCode.l"
case 23:
#line 97 "CCode.l"
case 24:
#line 98 "CCode.l"
case 25:
#line 99 "CCode.l"
case 26:
#line 100 "CCode.l"
case 27:
#line 101 "CCode.l"
case 28:
YY_RULE_SETUP
#line 101 "CCode.l"
{id_actual = 8; lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext); strcpy(tipo_actual,"KEYWORDD"); defining = 1; return KEYWORD;}
	YY_BREAK
case 29:
#line 104 "CCode.l"
case 30:
#line 105 "CCode.l"
case 31:
#line 106 "CCode.l"
case 32:
#line 107 "CCode.l"
case 33:
#line 108 "CCode.l"
case 34:
#line 109 "CCode.l"
case 35:
#line 110 "CCode.l"
case 36:
#line 111 "CCode.l"
case 37:
#line 112 "CCode.l"
case 38:
#line 113 "CCode.l"
case 39:
#line 114 "CCode.l"
case 40:
#line 115 "CCode.l"
case 41:
YY_RULE_SETUP
#line 115 "CCode.l"
{id_actual = 8; lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext);strcpy(tipo_actual,"KEYWORDC"); return KEYWORD;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 118 "CCode.l"
{id_actual = 2; lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char));strcpy(lexema_actual,yytext); valor_actual = atoi(yytext); return NUMBER;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 120 "CCode.l"
{id_actual = 2; lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char));strcpy(tipo_actual,"IDEC"); strcpy(lexema_actual,yytext); valor_actual = atoi(yytext); return NUMBER;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 121 "CCode.l"
{id_actual = 2; lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(tipo_actual,"IHEX"); strcpy(lexema_actual,yytext); valor_actual = atoi(yytext); return NUMBER;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 124 "CCode.l"
{id_actual = 2; lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char));strcpy(tipo_actual,"FLOATD"); strcpy(lexema_actual,yytext); valor_actual = atof(yytext); return NUMBER;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 125 "CCode.l"
{id_actual = 2; lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char));strcpy(tipo_actual,"FLOATE"); strcpy(lexema_actual,yytext); valor_actual = atof(yytext); return NUMBER;}
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 128 "CCode.l"
{id_actual = 3; lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext);strcpy(tipo_actual,"CHARL"); return STRINGLITERAL;}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 130 "CCode.l"
{id_actual = 3; lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext);strcpy(tipo_actual,"STRL"); return STRINGLITERAL;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 135 "CCode.l"
{id_actual = 4;strcpy(tipo_actual,"OPARI");strcpy(lexema_actual,yytext); return OPERADOR;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 136 "CCode.l"
{id_actual = 4;lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char));  strcpy(lexema_actual,yytext);strcpy(tipo_actual,"OPAS");return OPERADOR;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 137 "CCode.l"
{id_actual = 4; strcpy(tipo_actual,"OPR");lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext); return OPERADOR;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 138 "CCode.l"
{id_actual = 4;strcpy(tipo_actual,"OPL"); lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext); return OPERADOR;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 139 "CCode.l"
{id_actual = 4;strcpy(tipo_actual,"OPB");lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext); return OPERADOR;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 140 "CCode.l"
{id_actual = 4;strcpy(tipo_actual,"OPDEIN"); lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext); return OPERADOR;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 141 "CCode.l"
{id_actual = 4;strcpy(tipo_actual,"OPO"); strcpy(lexema_actual,yytext); return OPERADOR;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 144 "CCode.l"
{id_actual = 5;lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char));  strcpy(lexema_actual,yytext);strcpy(tipo_actual,"PUNTAC");  return PUNCTUATOR;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 146 "CCode.l"
{id_actual = 5; lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext);strcpy(tipo_actual,"PUNCT");  return PUNCTUATOR;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 151 "CCode.l"
{id_actual = 1;strcpy(tipo_actual,"ID");lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext); return IDENTIFIER;}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 153 "CCode.l"
{id_actual = 6; lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext);strcpy(tipo_actual,"NL"); return NL;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 154 "CCode.l"
{id_actual = 6; lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext);strcpy(tipo_actual,"SPACE"); return NL;}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 161 "CCode.l"
{printf("Preprocesador if: %s\n",yytext);}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 162 "CCode.l"
{printf("Preprocesador else: %s\n",yytext);}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 163 "CCode.l"
{printf("Preprocesador endif: %s\n",yytext);}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 164 "CCode.l"
{printf("Preprocesador define: %s\n",yytext);}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 165 "CCode.l"
{printf("Preprocesador line: %s\n",yytext);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 167 "CCode.l"
{printf("Include: %s\n",yytext); BEGIN IFILE; }
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 169 "CCode.l"
{
			{ int c;
			  int indice = 0;
			  char filename[1024] = {0};
		
			  while((c = input()) && c != '\n');
			   }
				
			printf("Archivo include es: %s\n",yytext);
			BEGIN INITIAL;
			}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 181 "CCode.l"
{printf("Error en include\n");
			BEGIN INITIAL;
		}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 186 "CCode.l"
{printf("Caracter misterioso %s \n",yytext);}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IFILE):
#line 189 "CCode.l"
{id_actual = 7;  lexema_actual = (char *) calloc(strlen(yytext)+1,sizeof(char)); strcpy(lexema_actual,yytext); return END;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 190 "CCode.l"
ECHO;
	YY_BREAK
#line 1456 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 391 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 391 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 390);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 190 "CCode.l"



struct Token getToken(){
	int tipo_yylex = yylex();
	if (tipo_yylex != END){
		struct Token t2;
  		t2.lexema = (char*) malloc(strlen(lexema_actual));
		strcpy(t2.lexema, lexema_actual);
		strcpy(t2.tipo, tipo_actual);
		t2.id = id_actual;
		t2.valor = valor_actual;
		strcpy(lexema_actual,"");
		strcpy(tipo_actual,"");
		return t2;
	}
	else{
		termino = 1;
		return EmptyStruct;
	}
}


void escribir_tex(struct Token token){
	//printf("Id, lexema, tipo y valor: %d %s %s %d \n",token.id,token.lexema,token.tipo, token.valor);	
	if(token.id == 8){  //Keywords
		fprintf(archivo_salida,"%s%s%s \n","\\textbf{\\textcolor{DarkOrchid}{",token.lexema,"}}");
	}
	if(token.id == 1){ //Identifier
		str_replace(token.lexema,"_","\\_");
		
		//char *resultado = cambiar_palabra(token.lexema,"_","\\_");
		fprintf(archivo_salida,"%s%s%s \n","\\underline{\\textcolor{Thistle}{",token.lexema,"}}");  
	}
	if(token.id == 2){ //Number
		fprintf(archivo_salida,"%s%s%s \n","\\textcolor{CadetBlue}{",token.lexema,"}");
	}
	if(token.id == 3){ //Stringliteral
		str_replace(token.lexema,"\\n","\\\\\n");
		str_replace(token.lexema,"%","\\%");
		
		
		fprintf(archivo_salida,"%s%s%s \n","\\textit{\\textcolor{GreenYellow}{",token.lexema,"}}");
	}
	if(token.id == 4){ //Operador
		str_replace(token.lexema,"<","\\textless");
		str_replace(token.lexema,">","\\textgreater");
		if( strcmp(token.lexema,"^") == 0 ){fprintf(archivo_salida,"\\textcolor{JungleGreen}{\\textasciicircum}");}
		else if(strcmp(token.lexema,"~") == 0){fprintf(archivo_salida,"\\textcolor{JungleGreen}{$\\sim$}");}
		else if(strcmp(token.lexema,"<%") == 0 ){fprintf(archivo_salida,"\\textcolor{JungleGreen}{\\textless\\%}");}
		else if(strcmp(token.lexema,"--") == 0){fprintf(archivo_salida,"\\textcolor{JungleGreen}{-\\hspace{0.05cm}-}");}
		else if(strcmp(token.lexema,"&&") == 0){fprintf(archivo_salida,"\\textcolor{JungleGreen}{\\&\\&}");}
		else if(strcmp(token.lexema,"^=") == 0){fprintf(archivo_salida,"\\textcolor{JungleGreen}{\\textasciicircum =}");}
		else if(strcmp(token.lexema,"%:%:") == 0){fprintf(archivo_salida,"\\textcolor{JungleGreen}{\\%:\\%:}");}
		else if( strcmp(token.lexema,"%:") == 0 || strcmp(token.lexema,"%>") == 0  || strcmp(token.lexema,"&=") == 0  || strcmp(token.lexema,"&") == 0  || strcmp(token.lexema,"%") == 0  || strcmp(token.lexema,"%=") == 0 ){fprintf(archivo_salida,"\\textcolor{JungleGreen}{\\%s}",token.lexema);}
		else{ fprintf(archivo_salida,"%s%s%s \n","\\textcolor{JungleGreen}{",token.lexema,"}"); }
	}
	if(token.id == 5){ //Punctuator
		str_replace(token.lexema,"#","\\#");
		if(strcmp(token.lexema,"{") == 0 || strcmp(token.lexema,"}") == 0){fprintf(archivo_salida,"\\%s \n",token.lexema);}
		else{fprintf(archivo_salida,"%s \n",token.lexema);}
		
	}
	if(token.id == 6){ //Nl
		fprintf(archivo_salida,"%s \n","\\textcolor{black}{ } \\newline");
	}
}

void new_frame(){
	fprintf(archivo_salida,"%s \n","\\begin{frame}");
}

void cerrar_frame(){
	fprintf(archivo_salida,"%s \n","\\begin{multicols}{3}");
        fprintf(archivo_salida,"\t %s \n","\\begin{itemize}");
        fprintf(archivo_salida,"\t \t %s \n","\\item \\textcolor{DarkOrchid}{Keywords}");
        fprintf(archivo_salida,"\t \t %s \n","\\item \\textcolor{Thistle}{Identifiers}");
        fprintf(archivo_salida,"\t \t %s \n","\\item \\textcolor{CadetBlue}{Numbers}");
        fprintf(archivo_salida,"\t \t %s \n","\\item \\textcolor{GreenYellow}{String-literal}");
        fprintf(archivo_salida,"\t \t %s \n","\\item \\textcolor{JungleGreen}{Operators}");
        fprintf(archivo_salida,"\t \t %s \n","\\item \\textcolor{white}{Punctuators}");
        fprintf(archivo_salida,"\t %s \n","\\end{itemize}");
        fprintf(archivo_salida,"%s \n","\\end{multicols}");

	fprintf(archivo_salida,"%s \n \n","\\end{frame}");
}

void str_replace(char *target, const char *needle, const char *replacement)
{
    char buffer[1024] = { 0 };
    char *insert_point = &buffer[0];
    const char *tmp = target;
    size_t needle_len = strlen(needle);
    size_t repl_len = strlen(replacement);

    while (1) {
        const char *p = strstr(tmp, needle);

        // walked past last occurrence of needle; copy remaining part
        if (p == NULL) {
            strcpy(insert_point, tmp);
            break;
        }

        // copy part before needle
        memcpy(insert_point, tmp, p - tmp);
        insert_point += p - tmp;

        // copy replacement string
        memcpy(insert_point, replacement, repl_len);
        insert_point += repl_len;

        // adjust pointers, move on
        tmp = p + needle_len;
    }

    // write altered string back to target
    strcpy(target, buffer);
}



void crear_archivo_salida(){
	archivo_salida = fopen("archivo_salida.tex","w"); //w+
	fprintf(archivo_salida,"%s \n","\\documentclass[usenames,dvipsnames]{beamer}");
	fprintf(archivo_salida,"%s \n","\\usepackage{pgfplots}");
	fprintf(archivo_salida,"%s \n","\\usepackage{calc}");
	fprintf(archivo_salida,"%s \n","\\usepackage{ifthen}");
	fprintf(archivo_salida,"%s \n","\\usepackage{tikz}");
	fprintf(archivo_salida,"%s \n","\\pgfplotsset{compat=1.13}");
	fprintf(archivo_salida,"%s \n","\\usepackage{xcolor}");
	fprintf(archivo_salida,"%s \n","\\usepackage[utf8]{inputenc}");
	fprintf(archivo_salida,"%s \n \n \n","\\usepackage{multicol}");
	fprintf(archivo_salida,"%s \n","\\usepackage{lmodern}");
	fprintf(archivo_salida,"%s \n","\\setbeamercolor{normal text}{bg=black} %fondo negro");
	fprintf(archivo_salida,"%s \n","\\setbeamercolor{normal text}{fg=white} %letras blancas");
	fprintf(archivo_salida,"%s \n","\\setbeamercolor{white back}{bg=white} %fondo en graficos blanco");
	fprintf(archivo_salida,"%s \n","\\setbeamercolor{frametitle}{fg=Cyan} % titulos cyan");
	fprintf(archivo_salida,"%s \n \n","\\setbeamercolor*{title}{fg=Cyan} %titulo principal cyan");
	fprintf(archivo_salida,"%s \n","\\title{Proyecto 1}");
	fprintf(archivo_salida,"%s \n","\\author{Jos\\'e Pablo Murillo Vargas, Nicol Morice Sand\\'i}");
	fprintf(archivo_salida,"%s \n","\\institute[VFU]");
	fprintf(archivo_salida,"%s \n","{");
	fprintf(archivo_salida,"%s \n","\\inst{}");
	fprintf(archivo_salida,"%s \n","Instituto T\\'ecnol\\'ogico de Costa Rica");
	fprintf(archivo_salida,"%s \n","\\and");
	fprintf(archivo_salida,"%s \n","\\inst{}");
	fprintf(archivo_salida,"%s \n","Escuela de Ingenier\\'ia en Computaci\\'on");
	fprintf(archivo_salida,"%s \n","\\and");
	fprintf(archivo_salida,"%s \n","\\inst{}");
	fprintf(archivo_salida,"%s \n","Compiladores e Int\\'erpretes");
	fprintf(archivo_salida,"%s \n","}");
	fprintf(archivo_salida,"%s \n \n","\\date{19-09-2017}"); 
	fprintf(archivo_salida,"%s \n \n","\\begin{document}");
	fprintf(archivo_salida,"%s \n \n","\\frame{\\titlepage}");
	fprintf(archivo_salida,"%s \n","\\begin{frame}");
	fprintf(archivo_salida,"%s \n","\\frametitle{Explicaci\\'on del Scanner}");
	fprintf(archivo_salida,"%s \n","El scanning, o an\\'alisis l\\'exico es el proceso por el cu\\'al se toma el archivo fuente y se intenta de romper en pedacitos significativos llamados tokens.\\\\[0.2cm]");
	fprintf(archivo_salida,"%s \n","Los scanners funcionan al buscar patronos de car\\'acteres dentro del fuente. Una forma de expresar estos patronos es por medio de las \\textbf{expresiones regulares}. Por ejemplo el patrón [1-9][0-9]* ser\\'ia un patr\\'on \\'util para encontrar todos los n\\'umeros enteros dentro del archivo fuente.");
	fprintf(archivo_salida,"%s \n \n","\\end{frame}");
	fprintf(archivo_salida,"%s \n","\\begin{frame}");
	fprintf(archivo_salida,"%s \n","\\frametitle{Explicaci\\'on de Flex}");
	fprintf(archivo_salida,"%s \n","Flex (Fast lexical analyzer generator) es un programa que genera los analizadores l\\'exicos o scanners. Su prop\\'osito era mejorar las deficiencias y pulgas de Lex. \\\\[0.2cm]");
	fprintf(archivo_salida,"%s \n","Flex fue escrito originalmente por Jef Poskanzer y luego fu\\'e mejorado por Vern Paxson y Van Jacobson. \\\\[0.2cm]");
	fprintf(archivo_salida,"%s \n","Un programa en flex es usar un conjunto de expresiones regulares y escribir que acciones debe tomar cu\\'ando encuentre uno de estos en el fuente.\\\\[0.2cm]");
	fprintf(archivo_salida,"%s \n","Flex tambi\\'en traduce todas las expresiones regulares en una forma interna eficiente que le permite hacer match simult\\'aneo de todos los patrones con el archivo fuente.");
	fprintf(archivo_salida,"%s \n \n","\\end{frame}");
}


void cerrar_archivo_salida(){
	fprintf(archivo_salida,"%s \n","\\end{document}");
	fclose(archivo_salida);
	system("pdflatex archivo_salida.tex");
	system("evince archivo_salida.pdf");
}

void contador_tokens(int id){
	if(id == 8){id8++;}
	if(id == 1){id1++;}
	if(id == 2){id2++;}
	if(id == 3){id3++;}
	if(id == 4){id4++;}
	if(id == 5){id5++;}
}

void grafico_pie(){
	idf1 = id1; idf2 = id2;idf3 = id3; idf4 = id4;idf5 = id5; idf8 = id8;
	
	fprintf(archivo_salida,"%s \n","\\newcommand{\\slice}[5]{");
	fprintf(archivo_salida,"%s \n ","\\pgfmathparse{0.5*#1+0.5*#2}");
	fprintf(archivo_salida,"%s \n ","\\let\\midangle\\pgfmathresult");
	fprintf(archivo_salida,"%s \n ","\\draw[thick,fill=#5] (0,0) -- (#1:1) arc (#1:#2:1) -- cycle;");
	fprintf(archivo_salida,"%s \n ","\\node[label=\\midangle:#4] at (\\midangle:1) {};");
	fprintf(archivo_salida,"%s \n ","\\pgfmathparse{min((#2-#1-10)/110*(-0.3),0)}");
	fprintf(archivo_salida,"%s \n ","\\let\\temp\\pgfmathresult");
	fprintf(archivo_salida,"%s \n ","\\pgfmathparse{max(\\temp,-0.5) + 0.8}");
	fprintf(archivo_salida,"%s \n ","\\let\\innerpos\\pgfmathresult");
	fprintf(archivo_salida,"%s \n ","\\node at (\\midangle:\\innerpos) {#3};");
	fprintf(archivo_salida,"%s \n ","}");

	fprintf(archivo_salida,"%s \n \n","\\begin{frame}");

	fprintf(archivo_salida,"%s \n ","\\begin{tikzpicture}[scale=3]");

	fprintf(archivo_salida,"%s \n ","\\newcounter{a}");
	fprintf(archivo_salida,"%s \n ","\\newcounter{b}");

	fprintf(archivo_salida,"%s%.0f%s%.0f%s%.0f%s \n ","\\foreach \\p/\\t/\\c in {",idf8/(idf8+idf1+idf2+idf3+idf4+idf5

)*100,"/Keyword/DarkOrchid, ",idf1/(idf8+idf1+idf2+idf3+idf4+idf5

)*100,"/Identifier/Thistle, ",idf2/(idf8+idf1+idf2+idf3+idf4+idf5

)*100,"/Constant/CadetBlue,");
	fprintf(archivo_salida,"%s%.0f%s%.0f%s%.0f%s \n "," ",idf3/(idf8+idf1+idf2+idf3+idf4+idf5

)*100,"/String-literal/GreenYellow, ",idf4/(idf8+idf1+idf2+idf3+idf4+idf5

)*100,"/Operador/JungleGreen, ",idf5/(idf8+idf1+idf2+idf3+idf4+idf5

)*100,"/Punctuator/Apricot}");
	fprintf(archivo_salida,"%s \n ","  {");
	fprintf(archivo_salida,"%s \n ","\\setcounter{a}{\\value{b}}");
	fprintf(archivo_salida,"%s \n ","\\addtocounter{b}{\\p}");
	fprintf(archivo_salida,"%s \n ","\\slice{\\thea/100*360}");
	fprintf(archivo_salida,"%s \n ","{\\theb/100*360}");
	fprintf(archivo_salida,"%s \n ","{\\p\\%}{\\t}{\\c}");
fprintf(archivo_salida,"%s \n ","  }");

fprintf(archivo_salida,"%s \n ","\\end{tikzpicture}");


	fprintf(archivo_salida,"%s \n","\\end{frame}");
}

void hacer_grafico_histo1(){
	//id8 = 1000; id1 = 3000; id2 = 500; id3 = 350; id4 = 4000; id5 = 7890;
	int max = 700;
	int secuencia;
	int terminar = 0;
	if(id8 < 500 && id1 < 500 && id2 < 500 && id3 < 500 && id4 < 500 && id5 < 500){ secuencia = 50; max = 500;terminar =1;}
	while(terminar == 0){
		if(id8 < max && id1 < max && id2 < max && id3 < max && id4 < max && id5 < max){
			secuencia = max/7;
			terminar = 1;
		}
		else{
			max = max + 700;
		}	
	}
	hacer_grafico_histo2(secuencia,max);
	
}


void hacer_grafico_histo2(int secuencia,int maximo){
	printf("Secuencia: %d Maximo: %d \n",secuencia,maximo);

	fprintf(archivo_salida,"%s \n","\\usebeamercolor[bg]{white back}");
	fprintf(archivo_salida,"%s \n \n","\\begin{frame}");
	fprintf(archivo_salida,"%s \n","\\begin{figure}");
	fprintf(archivo_salida,"%s \n","\\centering");
	fprintf(archivo_salida,"%s \n","\\begin{tikzpicture}");
	fprintf(archivo_salida,"%s \n","\\begin{axis}[");
	fprintf(archivo_salida,"%s \n","    xbar stacked,");
	fprintf(archivo_salida,"%s \n","    legend style={");
	fprintf(archivo_salida,"%s \n","    legend columns=4,");
	fprintf(archivo_salida,"%s \n","	at={(xticklabel cs:0.5)},");
	fprintf(archivo_salida,"%s \n","	anchor=north,");
	fprintf(archivo_salida,"%s \n","	draw=none");
	fprintf(archivo_salida,"%s \n","    },");
	fprintf(archivo_salida,"%s \n","    ytick=data,");
	fprintf(archivo_salida,"%s \n","    axis y line*=none,");
	fprintf(archivo_salida,"%s \n","    axis x line*=bottom,");
	fprintf(archivo_salida,"%s \n","    tick label style={font=\\footnotesize},");
	fprintf(archivo_salida,"%s \n","    legend style={font=\\footnotesize},");
	fprintf(archivo_salida,"%s \n","    label style={font=\\footnotesize},");
	fprintf(archivo_salida,"%s%d%s%d%s \n","    xtick={0,",secuencia,",...,",maximo,"},");
	fprintf(archivo_salida,"%s \n","    width=.9\\textwidth,");
	fprintf(archivo_salida,"%s \n","    bar width=6mm,");
	fprintf(archivo_salida,"%s \n","    yticklabels={{Keyword},");
	fprintf(archivo_salida,"%s \n","    {Identifier},");
	fprintf(archivo_salida,"%s \n","    {Number},");
	fprintf(archivo_salida,"%s \n","    {String literal},"); 
	fprintf(archivo_salida,"%s \n","    {Operador},"); 
	fprintf(archivo_salida,"%s \n","    {Punctuator}},");
	fprintf(archivo_salida,"%s \n","    xmin=0,");
	fprintf(archivo_salida,"%s%d%s \n","    xmax=",maximo,","); 
	fprintf(archivo_salida,"%s \n","    area legend,");
	fprintf(archivo_salida,"%s \n","    y=8mm,");
	fprintf(archivo_salida,"%s \n","    enlarge y limits={abs=0.725},"); 
	fprintf(archivo_salida,"%s \n","    nodes near coords,");
	fprintf(archivo_salida,"%s \n","    nodes near coords style={text=white, at ={(\\pgfplotspointmeta,\\pgfplotspointy)},anchor=west},");
	fprintf(archivo_salida,"%s \n","    visualization depends on=y \\as \\pgfplotspointy,");
	fprintf(archivo_salida,"%s \n","    every axis plot/.append style={fill}");
	fprintf(archivo_salida,"%s \n","]");
	fprintf(archivo_salida,"%s \n","\\addplot[DarkOrchid] coordinates");
	fprintf(archivo_salida,"%s%d%s \n","  {(",id8,",0) (0,1) (0,2) (0,3) (0,4) (0,5)};"); //cantidad de keywords
	fprintf(archivo_salida,"%s \n","\\addplot[Thistle] coordinates");
	fprintf(archivo_salida,"%s%d%s \n","  {(0,0) (",id1,",1) (0,2) (0,3) (0,4) (0,5)};"); //cantidad de identifiers
	fprintf(archivo_salida,"%s \n","\\addplot[CadetBlue] coordinates");
	fprintf(archivo_salida,"%s%d%s \n","  {(0,0) (0,1) (",id2,",2) (0,3) (0,4) (0,5)};"); //cantidad de number
	fprintf(archivo_salida,"%s \n","\\addplot[GreenYellow] coordinates");
	fprintf(archivo_salida,"%s%d%s \n","  {(0,0) (0,1) (0,2) (",id3,",3) (0,4) (0,5)};"); //cantidad de string-literal
	fprintf(archivo_salida,"%s \n","\\addplot[JungleGreen] coordinates");
	fprintf(archivo_salida,"%s%d%s \n","  {(0,0) (0,1) (0,2) (0,3) (",id4,",4) (0,5)};"); //cantidad de operador
	fprintf(archivo_salida,"%s \n","\\addplot[Apricot] coordinates");
	fprintf(archivo_salida,"%s%d%s \n","  {(0,0) (0,1) (0,2) (0,3) (0,4) (",id5,",5)};"); //cantidad de punctuator
	fprintf(archivo_salida,"%s \n","\\end{axis}");
	fprintf(archivo_salida,"%s \n \n","\\end{tikzpicture}");
	fprintf(archivo_salida,"%s \n","\\label{fig:stats}");
	fprintf(archivo_salida,"%s \n \n","\\end{figure}");
	fprintf(archivo_salida,"%s \n","\\end{frame}");
}



int main (int argc, char** argv)
{
	crear_archivo_salida();
	struct Token t;
	int num_nl = 0; 
	new_frame();
	while(termino == 0){
	   t = getToken();
	   if(t.id != EmptyStruct.id && num_nl < 11){
		if(t.id == 6){
			if(strcmp(t.tipo,"NL") == 0){num_nl++;escribir_tex(t);}	 
			if(num_nl == 10) {num_nl = 0; cerrar_frame(); new_frame();
			}	
		}else{escribir_tex(t); contador_tokens(t.id);}

	   }
	}
	cerrar_frame();
	hacer_grafico_histo1();	
	grafico_pie();
	cerrar_archivo_salida();
		
}


